# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Progress
                                 A QGIS plugin
 demo toshow progress bar
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-06
        copyright            : (C) 2019 by Zoltan Siki
        email                : siki1958@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Progress class from file Progress.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .progress import Progress
    return Progress(iface)
